
###
GET /api/channel/5dbef4a24244c213bcbffd13 HTTP/1.1
Host: {{host}}

###
POST /api/channel/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"name": "aaa"
	, "description": "qeeeee1"
}

###
PUT /api/channel/5babbb4f65d1e624acdce3e0 HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"name": "bbb234"
	, "description": "qeeeee1"
}

###
DELETE /api/channel/5babae96140d2f2b002f772f HTTP/1.1
Host: {{host}}