
### Обновление обоих токенов по истечении срока действия refresh токена
POST /api/refresh-tokens/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"fingerprint": "5dfa99f6732767292c1af9cf",
	"refreshToken": "e7fb8713-1e2a-4cec-bab0-2a0b0f87b09c"
}
