
### Запрос на сброс пароля юзера
POST /api/reset-password/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"email": "ifirtree@gmail.com",
	"fingerprint": "5dfa99f6732767292c1af9cf"
}

### Смена пароля юзера
PUT /api/reset-password/ HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJleHBpcmVzSW4iOjE1Nzc1NDY4NTA5MDUsInVzZXJJZCI6IjVlMDNhNDk0YTI0ZDQyMTAxMDA4MTk0ZiIsInVzZXJSb2xlIjoidXNlciIsImlhdCI6MTU3NzU0NTY1MH0.eyrhBmqXJTbbpDOzgeB0bwqGVdeiGgbU1H9Qd477N6Kab8iuXZ93kwhttccR01NziOVPZ3k0Jp7eIXqPz1XPnA
Content-Type: application/json

{
	"oldPassword": "333"
	,"password": "1"
}

