
###
GET /api/user/5dbef4a24244c213bcbffd13 HTTP/1.1
Host: {{host}}

###
POST /api/user/ HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
	"name": "aaa"
	, "description": "qeeeee1"
}

###
PUT /api/user/5e03a494a24d42101008194f HTTP/1.1
Host: {{host}}
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJleHBpcmVzSW4iOjE1Nzc2NDE1MjM5MjEsInVzZXJJZCI6IjVlMDNhNDk0YTI0ZDQyMTAxMDA4MTk0ZiIsInVzZXJSb2xlIjoiYWRtaW4iLCJpYXQiOjE1Nzc2MzQzMjN9.aVSEEsP64_vtIADtug6qBBolXPAi8xN2Vy0-QHpmQgwzRyGJqUQqOrN3craR3PPsPmIBJkBIhItQISEcfLtj_A
Content-Type: application/json

{
	"role": "admin"
}

###
DELETE /api/user/5babae96140d2f2b002f772f HTTP/1.1
Host: {{host}}